### ISSUE TITLE
Possibility to follow file moves?

### ISSUE THREAD

**Issue by cpaulik** [pidu/git-timemachine#33]
Hi, 
Do you know if it would be possible to let git timemachine follow the changes if the file moved? 

I already tried to add the `--follow` option [here](https://github.com/pidu/git-timemachine/blob/master/git-timemachine.el#L57) but as soon as the file moved I get an error that the file does not exist on disk

**Comment by pidu** [comment]
Adding `--follow` only gets you half way. You need to supply the correct file name to `git show` to properly move between renames in the file history. I would be interested in having this work but at first glance there is no _elegant_ way to instruct git log to print the actual file name. One could add `--name-only` but the output is then split over several lines so that would have to be handled. 

Then the file name for the revision in the history produced by adding --follow and --name-only would have to be used in the git show command. Doesn't sound  too hard typing this. Maybe you would like to have a go at it.

**Comment by pidu** [comment]
I had some time over so I made the suggested changes in 02e52b3

**Comment by cpaulik** [comment]
Thanks, my elisp skills would not yet have been up to the task.
