### ISSUE TITLE
Key bindings

### ISSUE THREAD

**Issue by fniessen** [pidu/git-timemachine#35]
A suggestion: wouldn't you use "h" and "H" for copying the commit hashes (instead of "w" and "W")?

**Comment by pidu** [comment]
Not unless there is a good case to be made. Everyone have their own favorite key bindings and they are easy to adjust yourself if you don't like the defaults. In my case I choose w and W because I think they make since (similar to C-w which is used throughout emacs and also to copy sha in magit). I'd also rather not upset people now being used to the defaults.

**Comment by fniessen** [comment]
No problem. This was just a suggestion. But I did not know about Magit defaults as well...
