### ISSUE TITLE
command to rollback to currently displayed version

### ISSUE THREAD

**Issue by vemv** [pidu/git-timemachine#63]
Hey there,

ace plugin!

There doesn't seem a command for overwriting the actual file with the currently-shown revision?

i.e. do a rollback.

Cheers - Victor

**Comment by pidu** [comment]
It's because `write-file` is already there and it's all you need. What file to overwrite is not necessarily clear because you could potentially have been following the history of a file that was renamed, there could be local changes and overwriting them without prompting the user is also a concern. It's been suggested before but if you want you can easily map write-file to a key of your choice in git-timemachine-mode-map.

**Comment by vemv** [comment]
Understood! Thanks for the explanation.

You might want to add it as a FAQ in the readme

**Comment by pidu** [comment]
Will do.
